In [ ]:
from numpy import array
from numpy import mean
from numpy import cov
from numpy.linalg import eig
import numpy as np
import select as sl

In [ ]:
A = array([[1,2], [3,4], [5,6]])
print(A)

[[1 2]
 [3 4]
 [5 6]]


In [ ]:
M = mean(A.T, axis=1) ##giá trị trung bình của từng cột ma trận
print(M)

[3. 4.]


In [ ]:
C = A - M # căn giữa(so sánh) các giá trị từng cột với giá trị trung bình
print(C)

[[-2. -2.]
 [ 0.  0.]
 [ 2.  2.]]


In [ ]:
V = cov(C.T) ## phương sai ma trận
print(V)

[[4. 4.]
 [4. 4.]]


In [ ]:
values, vectors = eig(V) # tính các vector riêng và giá trị riêng

In [ ]:
print(vectors)

[[ 0.70710678 -0.70710678]
 [ 0.70710678  0.70710678]]


In [ ]:
print(values) #từ giá trị này ta thấy vector thứ 2 hầu như không đóng góp quá nhiều dữ liệu nên ta có thể lược bỏ 

[8. 0.]


In [ ]:
P = vectors.T.dot(C.T)
print(P.T)

[[-2.82842712  0.        ]
 [ 0.          0.        ]
 [ 2.82842712  0.        ]]
