In [3]:
from numpy import array
from numpy import diag
from numpy import dot
from numpy import zeros
from scipy.linalg import svd

In [5]:
A = array([[1,1], [1, 1]])
print(A)

[[1 1]
 [1 1]]


In [6]:
U, s, VT = svd(A) ##sử dụng hàm 
print(U)


[[-0.70710678 -0.70710678]
 [-0.70710678  0.70710678]]


In [7]:
print(s)


[2. 0.]


In [8]:
print(VT)

[[-0.70710678 -0.70710678]
 [-0.70710678  0.70710678]]


In [11]:
Sigma = zeros((A.shape[0], A.shape[1]))## tạo ma trận với kích thước bằng ma trận A

In [12]:
print(Sigma)

[[0. 0.]
 [0. 0.]]


lấy các giá trị của s cho vào đường chéo 

In [13]:
Sigma[:A.shape[1], :A.shape[1]] = diag(s) ##lấy các giá trị từ s gán cho sigma

In [14]:
print(Sigma)

[[2. 0.]
 [0. 0.]]


Thử lại





In [15]:
B = U.dot(Sigma.dot(VT))

In [16]:
print(B)

[[1. 1.]
 [1. 1.]]


ma trận giả nghịch đảo


In [17]:
for i in range (0,s.shape[0]):
  if s[i]!=0:
    s[i]=1/s[i];

In [18]:
print(s)

[0.5 0. ]


In [19]:
Sigma = zeros((A.shape[0], A.shape[1]))

In [20]:
Sigma[:A.shape[1], :A.shape[1]] = diag(s) 

In [21]:
print(Sigma)

[[0.5 0. ]
 [0.  0. ]]


In [24]:
B = (VT.T).dot(Sigma.dot(U.T)) ##giả nghịch đảo ma trận a
print(B)

[[0.25 0.25]
 [0.25 0.25]]
